[package]
name = "tau"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/debatecore/tau"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
