#!/bin/bash
set -e

DB_PASSWORD=$(cat $DOCKER_DB_PASSWORD_FILE)

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER tau WITH PASSWORD '$DB_PASSWORD';
    CREATE DATABASE tau;
    GRANT CONNECT ON DATABASE tau TO tau;
    \c tau
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tau;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tau;
    GRANT USAGE, CREATE ON SCHEMA public TO tau;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO tau;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO tau;
EOSQL
