mod affiliations_tests;
mod auth_tests;
pub mod common;
mod debates_tests;
mod permissions_tests;
mod plans_tests;
mod roles_tests;
mod teams_tests;
mod teapot_tests;
mod tournament_tests;
mod verdicts_tests;
